include: package:lint/analysis_options.yaml
 
linter: 
  rules:
    - parameter_assignments
    
analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
